name: Windows Build
on: [push]
jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: cd ${{ github.workspace }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Clone janet
        run: cd ${{ github.workspace }} && git clone https://github.com/janet-lang/janet && cd janet
      - run: cd ${{ github.workspace }}/janet && build_win all
        shell: cmd
      #- run: cd ${{ github.workspace }}/janet && build_win test
      #  shell: cmd
      - run: dir %USERPROFILE%\AppData\Local
        shell: cmd
      - run: dir %USERPROFILE%\AppData\Local\Apps
        shell: cmd
      - run: dir %USERPROFILE%\AppData\Local\Apps\janet
        shell: cmd
      - run: dir %USERPROFILE%\AppData\Local\Apps\janet\bin
        shell: cmd
      - run: "%USERPROFILE%\\AppData\\Local\\Apps\\janet\\bin\\janet.exe -v"
        shell: cmd
        continue-on-error: true
      - name: List files in janet build
        run: |
          ls ${{ github.workspace }}/janet/build
      - run: echo "%USERPROFILE%\AppData\Local\Apps\janet\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - run: janet -v
        continue-on-error: true
        shell: cmd
      - run: echo %PATH%
        shell: cmd
      - run: echo %USERPROFILE%\AppData\Local\Apps\janet\bin >> $GITHUB_PATH
        shell: cmd
      - run: echo %PATH%
        shell: cmd
      - run: janet -v
        continue-on-error: true
        shell: cmd
      - name: Install jpm
        run: cd ${{ github.workspace }} && git clone https://github.com/janet-lang/jpm && cd jpm
        shell: cmd
      - run: set JANET_PATH=./ && set JANET_BINPATH=${{ github.workspace }}/janet/dist && set JANET_LIBPATH=${{ github.workspace }}/janet/dist && set JANET_HEADERPATH=${{ github.workspace }}/janet/dist && cd ${{ github.workspace }}/jpm && ${{ github.workspace }}/janet/dist/janet.exe bootstrap.janet
        shell: cmd
      - name: jpm deps
        run: cd ${{ github.workspace }} && jpm deps
      - name: jpm build
        run: jpm build
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - name: Create release
        run: gh release create windows-dont-use-this build/freja.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
